# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb4d576df50162c43fe12aa278be643872e4c6f29b86338cf1cea38144008b4ef5e1d53e1fa975acdffc2aec83a21f1228b7cf628ca9913a630be33d7173178

test:
  secret_key_base: 358d2842a84c653b6eeefc59cdfeae5cbd4ca02d94aa6acfe6581928b10f51b0b9b214f8777b55cb6728ee6e7e7e5e7cc43a7a70fc7d181718ff89fcdc0e563a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
